/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    Background: typeof import('./src/components/Background.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenshot: typeof import('./src/components/Screenshot.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    ValueTip: typeof import('./src/components/ValueTip.vue')['default']
  }
}
